### PR TITLE
Medical - Fix reposition UI actions

### LINKED ISSUE #296: Medical Circulation - Reposition user actions are available on characters who have died
**Mods (complete and add to the following information):**
- **Arma Reforger:** `1.6.0`
- **ACE Core:** `latest (medical/add-circulation)`
- _Other ACE mods for reproducing the issue_
None. Reproduced with ACE Medical Circulation Dev (inc. Medical Core Dev) + ACE Medical Hitzones Dev.

**Description:**
The Reposition ("Put in left recovery position", "Put in right recovery position" and "Put on back") user actions remain available on characters who have died (e.g., entered `CARDIAC ARREST` / `DEAD` life state). These actions should only be available for `INCAPACITATED` characters.

**Steps to reproduce:**
[See here](https://i.imgur.com/oPQ28We.gif)

1. Fatally wound a character so they enter the `INCAPACITATED` state.
2. Observe the reposition actions are correctly available.
3. Wait for the character to fully bleed out and transition to the `DEAD` life state.
4. Interact with the dead character's body.
5. See that the reposition actions are still present and selectable.

**Expected behavior:**
The reposition actions should not be visible or available on characters who are in the `DEAD` life state. They should only be usable on living characters who are `INCAPACITATED`.

**Which platform are you on?**
- PC (Workbench)

**Where did the issue occur?**
- Singleplayer (Workbench). The issue is in the action's display logic, so it likely affects Dedicated and Self-Hosted Multiplayer as well.

**Log Files:**
- N/A

**Additional context:**
The attached video shows the actions persisting after the character's vitals flatline. This is likely because the action's condition check uses `IsUnconscious()`, rather than checking for the specific `ECharacterLifeState.INCAPACITATED` life state.

### PR DESCRIPTION
**Pull request by denispol**
**When merged this pull request will:**

- **Enforce that the Reposition action runs exclusively on incapacitated characters, not dead targets**
- Update client visibility (`CanBeShownScript`) to check for the definitive `ECharacterLifeState.INCAPACITATED` status
- **Add a critical validation guard via `CanBePerformedScript`** to ensure execution integrity and prevent unauthorized action attempts
- Provide localized feedback by setting `m_sCannotPerformReason` when the action is rejected by the server

Closes #296

### CODE REVIEW

File: addons/medical_core/scripts/Game/ACE_Medical_Reposition/UserActions/ACE_Medical_RepositionUserAction.c [hunk 1]
```diff
@@ -48,6 +51,33 @@ class ACE_Medical_RepositionUserAction : ScriptedUserAction
 		
 		return true;
 	}
+
+	//------------------------------------------------------------------------------------------------
+	//! Can this action be performed by the provided user entity? (Server-side)
+	override bool CanBePerformedScript(IEntity user)
```
Comment (Kexanone) [inline addons/medical_core/scripts/Game/ACE_Medical_Reposition/UserActions/ACE_Medical_RepositionUserAction.c]: Both `CanBeShownScript` and `CanBePerformedScript` run on the client. The former determines whether the action is visible, while the latter whether it is greyed out with a cannot preform reason. We already only show the action when the character is incapacitated, so `CanBePerformedScript` serves no purpose.

**Review by Kexanone — CHANGES_REQUESTED** [review]

File: addons/medical_core/scripts/Game/ACE_Medical_Reposition/UserActions/ACE_Medical_RepositionUserAction.c (hunk 1 above)
Comment (denispol) [reply addons/medical_core/scripts/Game/ACE_Medical_Reposition/UserActions/ACE_Medical_RepositionUserAction.c]: OK, since we don't have any use case for the Reposition actions now beyond when life state == INCAPACITATED, client-side checks beyond UI visibility are not relevant. I then removed the CanBePerformed block and moved it actually server-side to the PerformAction() function as suggested.

**Comment by denispol** [comment]
I made the requested changes and also noticed a redundant NULL check on `ownerAnimComponent` and therefore simplified `if (!ownerAnimComponent || ownerAnimComponent.IsRagdollActive())` to `if (ownerAnimComponent.IsRagdollActive())` (null check already done one block above)

**Review by Kexanone — APPROVED** [review]
