### PR TITLE
Core - Fix load/save of deleted entities such as bushes and trees

### LINKED ISSUE #152: Core - `Wrong parameter value` on Linux Dedicated
```
Class:      'ACE_EditorStruct'
Function: 'ToString#2145496'
Stack trace:
scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c:24 Function ToString#2145496
scripts/Game/ACE_Core/Editor/Containers/Backend/ACE_EditorStruct.c:40 Function Serialize
scripts/Game/GameMode/SaveLoad/SCR_MissionStruct.c:72 Function Serialize
scripts/Game/GameMode/SaveLoad/SCR_DSSessionCallback.c:371 Function OnSaving
scripts/Game/GameMode/SaveLoad/SCR_DSSessionCallback.c:81 Function SaveSession
scripts/Game/GameMode/SaveLoad/SCR_SaveManagerCore.c:60 Function Save
scripts/Game/GameMode/SaveLoad/SCR_SaveLoadComponent.c:68 Function Autosave
scripts/Game/game.c:937 Function OnUpdate
```

The issue is that in `ACE_EntityIdHelper.c` the string length is assumed to be fixed and the value 18:

https://github.com/acemod/ACE-Anvil/blob/615fc578e79198bd3ab4145888f414d7a32d76c1/addons/core/scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c#L24

If the value is < then 18 characters in length, the value is now invalid, thus the `Wrong parameter value` error.

```c#
	static string ToString(EntityID id)
	{
		// Drop the last three characters, which are " {}"
		string str = id.ToString();
		return str.Substring(0, str.Length() - 3);
	}
```

This issue is also triggered when a mod is used that deletes elements like bushes/trees, which have very short IDs.

### PR DESCRIPTION
**Pull request by gnif**
This resolves #152, aka the "Wrong parameter value" error mentioned in #35. Patches contain comments to explain the exact cause and resolution of the issue.

### CODE REVIEW

File: addons/core/scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c [hunk 1]
```diff
@@ -4,23 +4,36 @@ class ACE_EntityIdHelper
 	//------------------------------------------------------------------------------------------------
 	static array<int> ToInt(EntityID id)
 	{
-		return ACE_HexTools.HexStringToInt(ToString(id));
+		array<int> bits = ACE_HexTools.HexStringToInt(ToString(id));
+		if (bits.Count() == 1)
+			bits.InsertAt(0, 0);
+
```
Comment (Kexanone) [inline addons/core/scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c:10]: `bits.Count() > 2` check is missing

File: addons/core/scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c [hunk 2]
```diff
@@ -4,23 +4,36 @@ class ACE_EntityIdHelper
...
+		return bits;
 	}
-	
+
 	//------------------------------------------------------------------------------------------------
 	static EntityID FromString(string str)
 	{
 		array<int> bits = ACE_HexTools.HexStringToInt(str);
```
Comment (Kexanone) [inline addons/core/scripts/Game/ACE_Core/Global/ACE_EntityIdHelper.c:17]: Use `ToInt` instead to avoid duplicate code below

**Review by Kexanone — CHANGES_REQUESTED** [review]
Thanks for the investigation and fix. Especially the `0x0x` prefix makes me suspect that there's a bug in the `pointer.ToString` method on Linux. I'll probably open a ticket for it. Btw. don't forget to add yourself as contributor to the AUTHORS file.

**Review by Kexanone — CHANGES_REQUESTED** [review]
We have to think about how to handle `0x(nil) {}`, which is what you get on Linux for the null pointer.

**Comment by gnif** [comment]
> We have to think about how to handle `0x(nil) {}`, which is what you get on Linux for the null pointer.

Since implenenting these fixes I have not seen this again, I am pretty sure it was happening because the old HexStringToInt was returning an empty array, which was then treated as EntitiID.INVALID, resulting in the `nil` value.

**Comment by Kexanone** [comment]
True, but I would argue that `ACE_EntityIdHelper` should nevertheless be able to handle `EntitiID.INVALID` as well.

**Comment by gnif** [comment]
Perhaps in `FromString` check for `0x(nil)` and return `EntityId.INVALID` if we see it?

**Comment by Kexanone** [comment]
Or we write it as `0x0` when we see it in `ToString`

**Comment by gnif** [comment]
I think we should do both actually, people upgrading with existing saves will have files full of `0x(nil)` values to be cleaned up.

**Comment by Kexanone** [comment]
Also handle the unprefixed version `(nil)` in `ToString` in case BI decides to fix it after all.

**Comment by gnif** [comment]
Done, and included handling of invalid IDs when loading the save

**Comment by gnif** [comment]
Just FYI, I have now tested this and everything is working as expected.

**Review by Kexanone — APPROVED** [review]
