### PR TITLE
Chopping - Replace ActionsManagerComponent on plant with helper

### LINKED ISSUE #50: Chopping - Memory related crashes
Has a high memory requirement, which may lead to memory-related crashes

### PR DESCRIPTION
**Pull request by Kexanone**
**When merged this pull request will:**
- Reduce memory requirement by using a dynamic spawned helper entity for providing the chopping action instead of an actions manager on all plants.
- Resolves #50

**Notes on the implementation:**
- The E-tool already has a dynamic handler for spawning/despawning building previews, hence we just use those methods for our helper system.

### CODE REVIEW

File: addons/chopping/scripts/Game/ACE_Chopping/Configs/ACE_Chopping_Config.c [hunk 1]
```diff
@@ -0,0 +1,58 @@
...
+		if (!prefabData)
+			return null;
+		
+		BaseContainer container = prefabData.GetPrefab();
+		if (!container)
+			return null;
+		
+		foreach (ACE_Chopping_ConfigEntry entry: m_aEntries)
+		{
+			if (!SCR_BaseContainerTools.IsKindOf(container, entry.m_sPlantPrefabName))
```
Comment (veteran29) [inline addons/chopping/scripts/Game/ACE_Chopping/Configs/ACE_Chopping_Config.c:22]: Probably does not matter much but I guess this could be cached in a `map`.

**Review by veteran29 — APPROVED** [review]
Great solution!
